# Generated by Django 3.2.7 on 2021-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211106_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='category',
            field=models.CharField(choices=[('Makalah', 'Makalah'), ('Artikel', 'Artikel'), ('Skripsi', 'Skripsi'), ('Kertas Kerja', 'Kertas Kerja'), ('Paper', 'Paper'), ('Tesis', 'Tesis'), ('Disertasi', 'Disertasi')], max_length=254),
        ),
    ]
