# Generated by Django 3.2.7 on 2021-12-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_karyailmiah_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='chosen_proposer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='max_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='review',
            name='max_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='review',
            name='max_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='review',
            name='max_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='review',
            name='max_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='score_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='plagiarism_percentage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_1',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_2',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_3',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_4',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
