# Generated by Django 3.2.7 on 2021-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('users_name', models.CharField(max_length=30)),
                ('users_status', models.CharField(max_length=30)),
            ],
        ),
    ]
