# Generated by Django 3.2.7 on 2021-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfeatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_status',
            field=models.BooleanField(default=False),
        ),
    ]
