# Generated by Django 3.2.7 on 2021-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminfeatures', '0002_alter_users_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_status',
            field=models.CharField(max_length=30),
        ),
    ]
